2025-06-20 16:17:21,002 - root - INFO - Initializing Trading Bot (Version 2025)...
2025-06-20 16:17:21,002 - root - INFO - Bot initialized in TEST environment.
2025-06-20 16:17:21,003 - root - INFO - --- Running new cycle for BTC-USDT-SWAP ---
2025-06-20 16:17:21,187 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "C:\Users\DEV\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'EMA_12'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 67, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 23, in run_cycle
    ta_score, df = self.ta_engine.calculate_technical_score(klines)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\modules\ta_engine.py", line 27, in calculate_technical_score
    if latest['EMA_12'] > latest['EMA_26']: score += 6
       ~~~~~~^^^^^^^^^^
  File "C:\Users\DEV\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEV\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'EMA_12'
2025-06-20 16:27:07,011 - root - INFO - Initializing Trading Bot (Version 2025)...
2025-06-20 16:27:07,012 - root - INFO - Bot initialized in TEST environment.
2025-06-20 16:27:07,012 - root - INFO - --- Running new cycle for BTC-USDT-SWAP ---
2025-06-20 16:27:07,201 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'EMA_12'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 67, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 23, in run_cycle
    ta_score, df = self.ta_engine.calculate_technical_score(klines)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\modules\ta_engine.py", line 27, in calculate_technical_score
    if latest['EMA_12'] > latest['EMA_26']: score += 6
       ~~~~~~^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'EMA_12'
2025-06-20 16:28:07,207 - root - INFO - --- Running new cycle for BTC-USDT-SWAP ---
2025-06-20 16:28:07,358 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'EMA_12'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 67, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 23, in run_cycle
    ta_score, df = self.ta_engine.calculate_technical_score(klines)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\modules\ta_engine.py", line 27, in calculate_technical_score
    if latest['EMA_12'] > latest['EMA_26']: score += 6
       ~~~~~~^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'EMA_12'
2025-06-20 16:29:07,362 - root - INFO - --- Running new cycle for BTC-USDT-SWAP ---
2025-06-20 16:29:07,508 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'EMA_12'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 67, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 23, in run_cycle
    ta_score, df = self.ta_engine.calculate_technical_score(klines)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\modules\ta_engine.py", line 27, in calculate_technical_score
    if latest['EMA_12'] > latest['EMA_26']: score += 6
       ~~~~~~^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'EMA_12'
2025-06-20 16:30:07,512 - root - INFO - --- Running new cycle for BTC-USDT-SWAP ---
2025-06-20 16:30:07,655 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'EMA_12'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 67, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 23, in run_cycle
    ta_score, df = self.ta_engine.calculate_technical_score(klines)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\modules\ta_engine.py", line 27, in calculate_technical_score
    if latest['EMA_12'] > latest['EMA_26']: score += 6
       ~~~~~~^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'EMA_12'
2025-06-20 16:31:07,659 - root - INFO - --- Running new cycle for BTC-USDT-SWAP ---
2025-06-20 16:31:07,797 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'EMA_12'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 67, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 23, in run_cycle
    ta_score, df = self.ta_engine.calculate_technical_score(klines)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\modules\ta_engine.py", line 27, in calculate_technical_score
    if latest['EMA_12'] > latest['EMA_26']: score += 6
       ~~~~~~^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'EMA_12'
2025-06-20 16:32:07,801 - root - INFO - --- Running new cycle for BTC-USDT-SWAP ---
2025-06-20 16:32:07,974 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'EMA_12'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 67, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 23, in run_cycle
    ta_score, df = self.ta_engine.calculate_technical_score(klines)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\modules\ta_engine.py", line 27, in calculate_technical_score
    if latest['EMA_12'] > latest['EMA_26']: score += 6
       ~~~~~~^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'EMA_12'
2025-06-20 16:33:07,980 - root - INFO - --- Running new cycle for BTC-USDT-SWAP ---
2025-06-20 16:33:08,124 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'EMA_12'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 67, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 23, in run_cycle
    ta_score, df = self.ta_engine.calculate_technical_score(klines)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\modules\ta_engine.py", line 27, in calculate_technical_score
    if latest['EMA_12'] > latest['EMA_26']: score += 6
       ~~~~~~^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'EMA_12'
2025-06-20 16:34:08,128 - root - INFO - --- Running new cycle for BTC-USDT-SWAP ---
2025-06-20 16:34:08,272 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'EMA_12'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 67, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 23, in run_cycle
    ta_score, df = self.ta_engine.calculate_technical_score(klines)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\modules\ta_engine.py", line 27, in calculate_technical_score
    if latest['EMA_12'] > latest['EMA_26']: score += 6
       ~~~~~~^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\venv\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'EMA_12'
2025-06-20 16:34:43,543 - root - INFO - Initializing Trading Bot (Version 2025)...
2025-06-20 16:34:43,543 - root - INFO - Bot initialized in TEST environment.
2025-06-20 16:34:43,543 - root - INFO - --- Running new cycle for BTC-USDT-SWAP ---
2025-06-20 16:34:43,705 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 64.51, EMA_12: 105622.61)
2025-06-20 16:34:43,705 - modules.ai_context_engine - INFO - AI Context Dummy Score: -0.72
2025-06-20 16:34:43,706 - modules.live_event_engine - INFO - Live Event Dummy Score: -2.94
2025-06-20 16:34:43,706 - root - INFO - FINAL SCORE: 3.65
2025-06-20 16:34:43,707 - root - INFO - DECISION: HOLD
2025-06-20 16:34:43,707 - root - INFO - Cycle finished. Waiting for 15m...
2025-06-20 16:42:00,199 - root - INFO - Bot stopped by user.
2025-06-20 16:42:25,145 - root - INFO - Initializing Trading Bot (Version 2025)...
2025-06-20 16:42:25,146 - root - INFO - Bot initialized in TEST environment.
2025-06-20 16:42:25,146 - root - INFO - --- Running new cycle for BTC-USDT-SWAP ---
2025-06-20 16:42:25,379 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 65.20, EMA_12: 105629.21)
2025-06-20 16:42:25,379 - modules.ai_context_engine - INFO - AI Context Dummy Score: 0.46
2025-06-20 16:42:25,380 - modules.live_event_engine - INFO - Live Event Dummy Score: -0.21
2025-06-20 16:42:25,380 - root - INFO - FINAL SCORE: 4.24
2025-06-20 16:42:25,381 - root - INFO - DECISION: HOLD
2025-06-20 16:42:25,381 - root - INFO - Cycle finished. Waiting for 15m...
2025-06-20 16:42:31,641 - root - INFO - Bot stopped by user.
2025-06-20 16:42:47,861 - root - INFO - Initializing Trading Bot (Version 2025)...
2025-06-20 16:42:47,861 - root - INFO - Bot initialized in TEST environment.
2025-06-20 16:42:47,862 - root - INFO - --- Running new cycle for SUI-USDT-SWAP ---
2025-06-20 16:42:48,008 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 54.35, EMA_12: 2.85)
2025-06-20 16:42:48,009 - modules.ai_context_engine - INFO - AI Context Dummy Score: 0.12
2025-06-20 16:42:48,009 - modules.live_event_engine - INFO - Live Event Dummy Score: 1.45
2025-06-20 16:42:48,010 - root - INFO - FINAL SCORE: 4.44
2025-06-20 16:42:48,010 - root - INFO - DECISION: HOLD
2025-06-20 16:42:48,011 - root - INFO - Cycle finished. Waiting for 15m...
2025-06-20 16:57:48,013 - root - INFO - --- Running new cycle for SUI-USDT-SWAP ---
2025-06-20 16:57:48,208 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 53.37, EMA_12: 2.84)
2025-06-20 16:57:48,209 - modules.ai_context_engine - INFO - AI Context Dummy Score: 0.47
2025-06-20 16:57:48,210 - modules.live_event_engine - INFO - Live Event Dummy Score: -1.53
2025-06-20 16:57:48,210 - root - INFO - FINAL SCORE: 4.04
2025-06-20 16:57:48,211 - root - INFO - DECISION: HOLD
2025-06-20 16:57:48,212 - root - INFO - Cycle finished. Waiting for 15m...
2025-06-20 17:09:55,185 - root - INFO - Bot stopped by user.
2025-06-20 17:10:00,944 - root - INFO - Initializing Trading Bot (Version 2025)...
2025-06-20 17:10:00,944 - root - INFO - Bot initialized in TEST environment.
2025-06-20 17:10:00,945 - root - INFO - --- Running new cycle for SUI-USDT-SWAP ---
2025-06-20 17:10:01,133 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 48.57, EMA_12: 2.84)
2025-06-20 17:10:01,134 - modules.ai_context_engine - INFO - AI Context Dummy Score: 0.76
2025-06-20 17:10:01,135 - modules.live_event_engine - INFO - Live Event Dummy Score: 1.17
2025-06-20 17:10:01,135 - root - INFO - FINAL SCORE: 4.49
2025-06-20 17:10:01,136 - root - INFO - DECISION: HOLD
2025-06-20 17:10:01,136 - root - INFO - Cycle finished. Waiting for 15m...
2025-06-20 17:25:01,138 - root - INFO - --- Running new cycle for SUI-USDT-SWAP ---
2025-06-20 17:25:01,332 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 54.12, EMA_12: 2.84)
2025-06-20 17:25:01,333 - modules.ai_context_engine - INFO - AI Context Dummy Score: -1.02
2025-06-20 17:25:01,333 - modules.live_event_engine - INFO - Live Event Dummy Score: 2.70
2025-06-20 17:25:01,334 - root - INFO - FINAL SCORE: 4.45
2025-06-20 17:25:01,335 - root - INFO - DECISION: HOLD
2025-06-20 17:25:01,335 - root - INFO - Cycle finished. Waiting for 15m...
2025-06-20 17:40:01,337 - root - INFO - --- Running new cycle for SUI-USDT-SWAP ---
2025-06-20 17:40:01,516 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 54.91, EMA_12: 2.85)
2025-06-20 17:40:01,516 - modules.ai_context_engine - INFO - AI Context Dummy Score: -0.16
2025-06-20 17:40:01,517 - modules.live_event_engine - INFO - Live Event Dummy Score: 0.71
2025-06-20 17:40:01,518 - root - INFO - FINAL SCORE: 4.28
2025-06-20 17:40:01,518 - root - INFO - DECISION: HOLD
2025-06-20 17:40:01,519 - root - INFO - Cycle finished. Waiting for 15m...
2025-06-20 17:55:01,520 - root - INFO - --- Running new cycle for SUI-USDT-SWAP ---
2025-06-20 17:55:01,723 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.77, EMA_12: 2.85)
2025-06-20 17:55:01,723 - modules.ai_context_engine - INFO - AI Context Dummy Score: -0.19
2025-06-20 17:55:01,724 - modules.live_event_engine - INFO - Live Event Dummy Score: 2.32
2025-06-20 17:55:01,724 - root - INFO - FINAL SCORE: 4.52
2025-06-20 17:55:01,725 - root - INFO - DECISION: HOLD
2025-06-20 17:55:01,725 - root - INFO - Cycle finished. Waiting for 15m...
2025-06-20 18:10:01,727 - root - INFO - --- Running new cycle for SUI-USDT-SWAP ---
2025-06-20 18:10:01,931 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 50.42, EMA_12: 2.85)
2025-06-20 18:10:01,932 - modules.ai_context_engine - INFO - AI Context Dummy Score: 0.27
2025-06-20 18:10:01,933 - modules.live_event_engine - INFO - Live Event Dummy Score: -2.69
2025-06-20 18:10:01,934 - root - INFO - FINAL SCORE: 3.84
2025-06-20 18:10:01,934 - root - INFO - DECISION: HOLD
2025-06-20 18:10:01,935 - root - INFO - Cycle finished. Waiting for 15m...
2025-06-20 18:25:01,937 - root - INFO - --- Running new cycle for SUI-USDT-SWAP ---
2025-06-20 18:25:02,146 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 49.79, EMA_12: 2.85)
2025-06-20 18:25:02,147 - modules.ai_context_engine - INFO - AI Context Dummy Score: 1.41
2025-06-20 18:25:02,148 - modules.live_event_engine - INFO - Live Event Dummy Score: -0.72
2025-06-20 18:25:02,148 - root - INFO - FINAL SCORE: 4.30
2025-06-20 18:25:02,149 - root - INFO - DECISION: HOLD
2025-06-20 18:25:02,150 - root - INFO - Cycle finished. Waiting for 15m...
2025-06-20 18:40:02,151 - root - INFO - --- Running new cycle for SUI-USDT-SWAP ---
2025-06-20 18:40:02,397 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 48.79, EMA_12: 2.85)
2025-06-20 18:40:02,398 - modules.ai_context_engine - INFO - AI Context Dummy Score: 0.47
2025-06-20 18:40:02,399 - modules.live_event_engine - INFO - Live Event Dummy Score: -2.94
2025-06-20 18:40:02,400 - root - INFO - FINAL SCORE: 3.83
2025-06-20 18:40:02,400 - root - INFO - DECISION: HOLD
2025-06-20 18:40:02,402 - root - INFO - Cycle finished. Waiting for 15m...
2025-06-20 18:55:02,405 - root - INFO - --- Running new cycle for SUI-USDT-SWAP ---
2025-06-20 18:55:02,607 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 48.44, EMA_12: 2.85)
2025-06-20 18:55:02,608 - modules.ai_context_engine - INFO - AI Context Dummy Score: -1.62
2025-06-20 18:55:02,609 - modules.live_event_engine - INFO - Live Event Dummy Score: -0.71
2025-06-20 18:55:02,609 - root - INFO - FINAL SCORE: 3.85
2025-06-20 18:55:02,610 - root - INFO - DECISION: HOLD
2025-06-20 18:55:02,610 - root - INFO - Cycle finished. Waiting for 15m...
2025-06-20 19:10:02,611 - root - INFO - --- Running new cycle for SUI-USDT-SWAP ---
2025-06-20 19:10:02,797 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 47.31, EMA_12: 2.85)
2025-06-20 19:10:02,797 - modules.ai_context_engine - INFO - AI Context Dummy Score: 0.05
2025-06-20 19:10:02,798 - modules.live_event_engine - INFO - Live Event Dummy Score: 1.29
2025-06-20 19:10:02,798 - root - INFO - FINAL SCORE: 4.40
2025-06-20 19:10:02,799 - root - INFO - DECISION: HOLD
2025-06-20 19:10:02,799 - root - INFO - Cycle finished. Waiting for 15m...
2025-06-20 19:25:02,800 - root - INFO - --- Running new cycle for SUI-USDT-SWAP ---
2025-06-20 19:25:02,977 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 48.10, EMA_12: 2.85)
2025-06-20 19:25:02,977 - modules.ai_context_engine - INFO - AI Context Dummy Score: -1.37
2025-06-20 19:25:02,978 - modules.live_event_engine - INFO - Live Event Dummy Score: -2.22
2025-06-20 19:25:02,978 - root - INFO - FINAL SCORE: 3.66
2025-06-20 19:25:02,979 - root - INFO - DECISION: HOLD
2025-06-20 19:25:02,980 - root - INFO - Cycle finished. Waiting for 15m...
2025-06-20 19:40:02,981 - root - INFO - --- Running new cycle for SUI-USDT-SWAP ---
2025-06-20 19:40:03,168 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 55.05, EMA_12: 2.85)
2025-06-20 19:40:03,169 - modules.ai_context_engine - INFO - AI Context Dummy Score: -1.84
2025-06-20 19:40:03,170 - modules.live_event_engine - INFO - Live Event Dummy Score: 1.70
2025-06-20 19:40:03,170 - root - INFO - FINAL SCORE: 4.18
2025-06-20 19:40:03,170 - root - INFO - DECISION: HOLD
2025-06-20 19:40:03,171 - root - INFO - Cycle finished. Waiting for 15m...
2025-06-20 19:45:22,413 - root - INFO - Bot stopped by user.
2025-06-20 19:45:31,305 - root - INFO - Initializing Trading Bot (Version 2025)...
2025-06-20 19:45:31,306 - root - INFO - Bot initialized in TEST environment.
2025-06-20 19:45:31,306 - root - INFO - --- Running new cycle for SUI-USDT-SWAP ---
2025-06-20 19:45:31,498 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 54.21, EMA_12: 2.85)
2025-06-20 19:45:31,499 - modules.ai_context_engine - INFO - AI Context Dummy Score: 0.25
2025-06-20 19:45:31,500 - modules.live_event_engine - INFO - Live Event Dummy Score: 0.98
2025-06-20 19:45:31,500 - root - INFO - FINAL SCORE: 4.38
2025-06-20 19:45:31,500 - root - INFO - DECISION: HOLD
2025-06-20 19:45:31,501 - root - INFO - Cycle finished. Waiting for 15m...
2025-06-20 19:48:50,367 - root - INFO - Bot stopped by user.
2025-06-20 19:59:18,132 - root - INFO - Initializing Trading Bot (Version 2025)...
2025-06-20 19:59:18,132 - root - INFO - Bot initialized in TEST environment.
2025-06-20 19:59:18,133 - root - INFO - --- Running new cycle for SUI-USDT-SWAP ---
2025-06-20 19:59:18,351 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 53.09, EMA_12: 2.85)
2025-06-20 19:59:18,352 - modules.ai_context_engine - INFO - AI Context Dummy Score: 1.11
2025-06-20 19:59:18,352 - modules.live_event_engine - INFO - Live Event Dummy Score: 2.84
2025-06-20 19:59:18,352 - root - INFO - FINAL SCORE: 4.79
2025-06-20 19:59:18,353 - root - INFO - DECISION: HOLD
2025-06-20 19:59:18,353 - root - INFO - Cycle finished. Waiting for 15m...
2025-06-20 19:59:23,522 - root - INFO - Bot stopped by user.
2025-06-21 08:28:48,702 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 08:28:48,704 - root - INFO - Bot initialized in TEST environment.
2025-06-21 08:28:48,704 - root - INFO - --- Running new cycle for SUI-USDT-SWAP ---
2025-06-21 08:28:48,917 - modules.api_integration - INFO - Successfully fetched 300 klines for SUI-USDT-SWAP
2025-06-21 08:28:48,947 - modules.ta_engine - INFO - TA Score Calculated: -6.00 (RSI: 46.75, EMA_12: 2.72)
2025-06-21 08:28:48,948 - root - INFO - Checking for entry signal. Current TA Score: -6.00
2025-06-21 08:28:48,949 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 08:43:48,951 - root - INFO - --- Running new cycle for SUI-USDT-SWAP ---
2025-06-21 08:43:49,161 - modules.api_integration - INFO - Successfully fetched 300 klines for SUI-USDT-SWAP
2025-06-21 08:43:49,194 - modules.ta_engine - INFO - TA Score Calculated: -6.00 (RSI: 48.84, EMA_12: 2.72)
2025-06-21 08:43:49,194 - root - INFO - Checking for entry signal. Current TA Score: -6.00
2025-06-21 08:43:49,194 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 08:58:49,204 - root - INFO - --- Running new cycle for SUI-USDT-SWAP ---
2025-06-21 08:58:49,403 - modules.api_integration - INFO - Successfully fetched 300 klines for SUI-USDT-SWAP
2025-06-21 08:58:49,439 - modules.ta_engine - INFO - TA Score Calculated: -6.00 (RSI: 48.72, EMA_12: 2.72)
2025-06-21 08:58:49,440 - root - INFO - Checking for entry signal. Current TA Score: -6.00
2025-06-21 08:58:49,442 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 09:13:49,444 - root - INFO - --- Running new cycle for SUI-USDT-SWAP ---
2025-06-21 09:13:49,643 - modules.api_integration - INFO - Successfully fetched 300 klines for SUI-USDT-SWAP
2025-06-21 09:13:49,656 - modules.ta_engine - INFO - TA Score Calculated: -6.00 (RSI: 52.06, EMA_12: 2.73)
2025-06-21 09:13:49,657 - root - INFO - Checking for entry signal. Current TA Score: -6.00
2025-06-21 09:13:49,658 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 09:41:15,586 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 09:41:15,586 - root - INFO - Bot initialized in TEST environment.
2025-06-21 09:41:15,586 - root - INFO - --- Running new cycle for PEPE-USDT-SWAP ---
2025-06-21 09:41:16,320 - modules.api_integration - INFO - Successfully fetched 300 klines for PEPE-USDT-SWAP
2025-06-21 09:41:16,355 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 63.06, EMA_12: 0.00)
2025-06-21 09:41:16,355 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 09:41:16,355 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 09:41:16,761 - modules.api_integration - ERROR - Error getting account balance: 401 Client Error: Unauthorized for url: https://www.okx.com/api/v5/account/balance?ccy=USDT
2025-06-21 09:41:16,761 - modules.api_integration - ERROR - Response: {"msg":"Request header OK-ACCESS-PASSPHRASE incorrect.","code":"50105"}
2025-06-21 09:41:16,761 - root - ERROR - Cannot place trade due to invalid balance.
2025-06-21 09:41:16,761 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 09:43:49,387 - root - INFO - Bot stopped by user.
2025-06-21 09:43:54,709 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 09:43:54,709 - root - INFO - Bot initialized in TEST environment.
2025-06-21 09:43:54,709 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 09:43:55,265 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 09:43:55,295 - modules.ta_engine - INFO - TA Score Calculated: -6.00 (RSI: 49.23, EMA_12: 0.16)
2025-06-21 09:43:55,299 - root - INFO - Checking for entry signal. Current TA Score: -6.00
2025-06-21 09:43:55,299 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 09:44:51,300 - root - INFO - Bot stopped by user.
2025-06-21 09:44:59,834 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 09:44:59,834 - root - INFO - Bot initialized in TEST environment.
2025-06-21 09:44:59,834 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 09:45:00,289 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 09:45:00,315 - modules.ta_engine - INFO - TA Score Calculated: -6.00 (RSI: 51.88, EMA_12: 0.16)
2025-06-21 09:45:00,315 - root - INFO - Checking for entry signal. Current TA Score: -6.00
2025-06-21 09:45:00,315 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 09:45:05,913 - root - INFO - Bot stopped by user.
2025-06-21 09:45:08,182 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 09:45:08,182 - root - INFO - Bot initialized in TEST environment.
2025-06-21 09:45:08,182 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 09:45:08,511 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 09:45:08,549 - modules.ta_engine - INFO - TA Score Calculated: -6.00 (RSI: 51.88, EMA_12: 0.16)
2025-06-21 09:45:08,549 - root - INFO - Checking for entry signal. Current TA Score: -6.00
2025-06-21 09:45:08,549 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 09:45:11,060 - root - INFO - Bot stopped by user.
2025-06-21 09:45:13,393 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 09:45:13,393 - root - INFO - Bot initialized in TEST environment.
2025-06-21 09:45:13,393 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 09:45:13,716 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 09:45:13,753 - modules.ta_engine - INFO - TA Score Calculated: -6.00 (RSI: 51.88, EMA_12: 0.16)
2025-06-21 09:45:13,755 - root - INFO - Checking for entry signal. Current TA Score: -6.00
2025-06-21 09:45:13,755 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 09:45:16,167 - root - INFO - Bot stopped by user.
2025-06-21 09:45:18,783 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 09:45:18,786 - root - INFO - Bot initialized in TEST environment.
2025-06-21 09:45:18,786 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 09:45:19,109 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 09:45:19,136 - modules.ta_engine - INFO - TA Score Calculated: -6.00 (RSI: 51.88, EMA_12: 0.16)
2025-06-21 09:45:19,136 - root - INFO - Checking for entry signal. Current TA Score: -6.00
2025-06-21 09:45:19,138 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 09:45:26,901 - root - INFO - Bot stopped by user.
2025-06-21 09:45:43,766 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 09:45:43,766 - root - INFO - Bot initialized in TEST environment.
2025-06-21 09:45:43,766 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 09:45:44,105 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 09:45:44,138 - modules.ta_engine - INFO - TA Score Calculated: -6.00 (RSI: 51.88, EMA_12: 0.16)
2025-06-21 09:45:44,138 - root - INFO - Checking for entry signal. Current TA Score: -6.00
2025-06-21 09:45:44,140 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 10:00:44,141 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 10:00:44,751 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 10:00:44,767 - modules.ta_engine - INFO - TA Score Calculated: -6.00 (RSI: 49.64, EMA_12: 0.16)
2025-06-21 10:00:44,767 - root - INFO - Checking for entry signal. Current TA Score: -6.00
2025-06-21 10:00:44,767 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 10:15:44,783 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 10:15:45,685 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 10:15:45,701 - modules.ta_engine - INFO - TA Score Calculated: -6.00 (RSI: 52.92, EMA_12: 0.16)
2025-06-21 10:15:45,701 - root - INFO - Checking for entry signal. Current TA Score: -6.00
2025-06-21 10:15:45,701 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 10:30:45,715 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 10:30:46,501 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 10:30:46,516 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 54.52, EMA_12: 0.16)
2025-06-21 10:30:46,516 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 10:30:46,516 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 10:30:47,567 - modules.api_integration - ERROR - Error getting account balance: 401 Client Error: Unauthorized for url: https://www.okx.com/api/v5/account/balance?ccy=USDT
2025-06-21 10:30:47,567 - modules.api_integration - ERROR - Response: {"msg":"Request header OK-ACCESS-PASSPHRASE incorrect.","code":"50105"}
2025-06-21 10:30:47,567 - root - ERROR - Cannot place trade due to invalid balance.
2025-06-21 10:30:47,567 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 10:42:44,517 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 10:42:44,517 - root - INFO - Bot initialized in TEST environment.
2025-06-21 10:42:44,517 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 10:42:45,407 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 10:42:45,437 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 54.52, EMA_12: 0.16)
2025-06-21 10:42:45,439 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 10:42:45,439 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 10:42:46,063 - modules.api_integration - INFO - Available balance for USDT: 54780.12080624591
2025-06-21 10:42:46,068 - modules.risk_management - INFO - Risk Calc: Balance=$54,780.12, Risk=$547.80, Size=532238.7974
2025-06-21 10:42:46,430 - modules.api_integration - INFO - Placing order: buy 532238.7974 DOGE-USDT-SWAP
2025-06-21 10:42:46,430 - root - ERROR - Failed to place trade. API Response: {'code': '1', 'data': [{'clOrdId': '', 'ordId': '', 'sCode': '51121', 'sMsg': 'Order quantity must be a multiple of the lot size.', 'tag': '', 'ts': '1750477367551'}], 'inTime': '1750477367551390', 'msg': 'All operations failed', 'outTime': '1750477367551567'}
2025-06-21 10:42:46,430 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 10:45:47,573 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 10:45:48,099 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 10:45:48,117 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 55.60, EMA_12: 0.16)
2025-06-21 10:45:48,117 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 10:45:48,125 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 10:45:48,440 - modules.api_integration - ERROR - Error getting account balance: 401 Client Error: Unauthorized for url: https://www.okx.com/api/v5/account/balance?ccy=USDT
2025-06-21 10:45:48,440 - modules.api_integration - ERROR - Response: {"msg":"Request header OK-ACCESS-PASSPHRASE incorrect.","code":"50105"}
2025-06-21 10:45:48,448 - root - ERROR - Cannot place trade due to invalid balance.
2025-06-21 10:45:48,448 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 10:47:53,931 - root - INFO - Bot stopped by user.
2025-06-21 10:48:01,999 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 10:48:01,999 - root - INFO - Bot initialized in TEST environment.
2025-06-21 10:49:43,875 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 10:49:43,875 - root - INFO - Bot initialized in TEST environment.
2025-06-21 10:49:43,875 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 10:49:44,382 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 10:49:44,402 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 55.60, EMA_12: 0.16)
2025-06-21 10:49:44,403 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 10:49:44,404 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 10:49:44,404 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 10:50:44,408 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 10:50:45,055 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 10:50:45,098 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 55.60, EMA_12: 0.16)
2025-06-21 10:50:45,098 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 10:50:45,098 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 10:50:45,098 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 10:51:45,107 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 10:51:45,884 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 10:51:45,918 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 55.60, EMA_12: 0.16)
2025-06-21 10:51:45,918 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 10:51:45,918 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 10:51:45,918 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 10:52:45,926 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 10:52:46,760 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 10:52:46,780 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 55.60, EMA_12: 0.16)
2025-06-21 10:52:46,782 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 10:52:46,782 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 10:52:46,782 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 10:53:46,787 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 10:53:47,220 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 10:53:47,243 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 55.60, EMA_12: 0.16)
2025-06-21 10:53:47,243 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 10:53:47,243 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 10:53:47,243 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 10:54:47,260 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 10:54:47,875 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 10:54:47,893 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 55.60, EMA_12: 0.16)
2025-06-21 10:54:47,893 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 10:54:47,893 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 10:54:47,893 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 10:55:47,901 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 10:55:48,750 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 10:55:48,770 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 55.60, EMA_12: 0.16)
2025-06-21 10:55:48,770 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 10:55:48,770 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 10:55:48,770 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 10:56:48,779 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 10:56:49,182 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 10:56:49,205 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 55.60, EMA_12: 0.16)
2025-06-21 10:56:49,206 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 10:56:49,207 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 10:56:49,207 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 10:57:49,212 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 10:57:49,509 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 10:57:49,532 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 55.60, EMA_12: 0.16)
2025-06-21 10:57:49,532 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 10:57:49,532 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 10:57:49,532 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 10:58:49,540 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 10:58:50,019 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 10:58:50,043 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 55.60, EMA_12: 0.16)
2025-06-21 10:58:50,046 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 10:58:50,047 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 10:58:50,047 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 10:59:50,051 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 10:59:50,617 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 10:59:50,640 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 55.60, EMA_12: 0.16)
2025-06-21 10:59:50,651 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 10:59:50,651 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 10:59:50,653 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:00:48,451 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:00:48,838 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:00:48,860 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 53.54, EMA_12: 0.16)
2025-06-21 11:00:48,860 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:00:48,860 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:00:49,144 - modules.api_integration - ERROR - Error getting account balance: 401 Client Error: Unauthorized for url: https://www.okx.com/api/v5/account/balance?ccy=USDT
2025-06-21 11:00:49,144 - modules.api_integration - ERROR - Response: {"msg":"Request header OK-ACCESS-PASSPHRASE incorrect.","code":"50105"}
2025-06-21 11:00:49,154 - root - ERROR - Cannot place trade due to invalid balance.
2025-06-21 11:00:49,154 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 11:00:50,657 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:00:50,959 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:00:50,976 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 53.54, EMA_12: 0.16)
2025-06-21 11:00:50,984 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:00:50,984 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:00:50,984 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:01:50,990 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:01:51,356 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:01:51,376 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 53.54, EMA_12: 0.16)
2025-06-21 11:01:51,376 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:01:51,376 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:01:51,376 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:02:51,382 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:02:51,769 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:02:51,789 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 53.54, EMA_12: 0.16)
2025-06-21 11:02:51,791 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:02:51,791 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:02:51,792 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:03:51,796 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:03:52,428 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:03:52,443 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 53.54, EMA_12: 0.16)
2025-06-21 11:03:52,443 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:03:52,443 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:03:52,459 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:04:52,462 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:04:52,802 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:04:52,825 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 53.54, EMA_12: 0.16)
2025-06-21 11:04:52,830 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:04:52,830 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:04:52,830 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:05:52,835 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:05:53,565 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:05:53,589 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 53.54, EMA_12: 0.16)
2025-06-21 11:05:53,589 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:05:53,589 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:05:53,589 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:06:53,599 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:06:54,115 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:06:54,131 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 53.54, EMA_12: 0.16)
2025-06-21 11:06:54,131 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:06:54,131 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:06:54,146 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:07:54,150 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:07:54,446 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:07:54,471 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 53.54, EMA_12: 0.16)
2025-06-21 11:07:54,471 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:07:54,471 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:07:54,471 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:08:54,480 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:08:57,300 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:08:57,329 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 53.54, EMA_12: 0.16)
2025-06-21 11:08:57,331 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:08:57,332 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:08:57,333 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:09:57,338 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:09:58,364 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:09:58,394 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 53.54, EMA_12: 0.16)
2025-06-21 11:09:58,394 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:09:58,394 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:09:58,397 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:10:58,400 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:10:58,778 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:10:58,811 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 53.54, EMA_12: 0.16)
2025-06-21 11:10:58,812 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:10:58,812 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:10:58,813 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:11:58,817 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:11:59,338 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:11:59,366 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 53.54, EMA_12: 0.16)
2025-06-21 11:11:59,367 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:11:59,367 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:11:59,369 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:12:59,372 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:12:59,710 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:12:59,738 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 53.54, EMA_12: 0.16)
2025-06-21 11:12:59,738 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:12:59,738 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:12:59,738 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:13:59,751 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:14:00,073 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:14:00,079 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 53.54, EMA_12: 0.16)
2025-06-21 11:14:00,079 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:14:00,079 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:14:00,079 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:15:00,094 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:15:00,387 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:15:00,426 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.16, EMA_12: 0.16)
2025-06-21 11:15:00,426 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:15:00,428 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:15:00,429 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:15:49,156 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:15:49,809 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:15:49,833 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.16, EMA_12: 0.16)
2025-06-21 11:15:49,834 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:15:49,835 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:15:50,212 - modules.api_integration - ERROR - Error getting account balance: 401 Client Error: Unauthorized for url: https://www.okx.com/api/v5/account/balance?ccy=USDT
2025-06-21 11:15:50,212 - modules.api_integration - ERROR - Response: {"msg":"Request header OK-ACCESS-PASSPHRASE incorrect.","code":"50105"}
2025-06-21 11:15:50,212 - root - ERROR - Cannot place trade due to invalid balance.
2025-06-21 11:15:50,212 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 11:16:00,432 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:16:00,708 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:16:00,732 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.16, EMA_12: 0.16)
2025-06-21 11:16:00,733 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:16:00,735 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:16:00,736 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:17:00,739 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:17:01,266 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:17:01,271 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.16, EMA_12: 0.16)
2025-06-21 11:17:01,280 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:17:01,280 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:17:01,280 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:18:01,285 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:18:01,621 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:18:01,644 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.16, EMA_12: 0.16)
2025-06-21 11:18:01,644 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:18:01,644 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:18:01,644 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:19:01,658 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:19:01,937 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:19:01,952 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.16, EMA_12: 0.16)
2025-06-21 11:19:01,968 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:19:01,968 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:19:01,968 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:20:01,972 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:20:02,270 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:20:02,271 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.16, EMA_12: 0.16)
2025-06-21 11:20:02,288 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:20:02,288 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:20:02,288 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:21:02,293 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:21:02,600 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:21:02,619 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.16, EMA_12: 0.16)
2025-06-21 11:21:02,619 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:21:02,619 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:21:02,619 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:22:02,627 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:22:03,017 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:22:03,035 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.16, EMA_12: 0.16)
2025-06-21 11:22:03,035 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:22:03,035 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:22:03,035 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:23:03,045 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:23:03,288 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:23:03,297 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.16, EMA_12: 0.16)
2025-06-21 11:23:03,297 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:23:03,312 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:23:03,312 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:24:03,317 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:24:03,564 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:24:03,583 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.16, EMA_12: 0.16)
2025-06-21 11:24:03,591 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:24:03,591 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:24:03,593 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:25:03,596 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:25:04,064 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:25:04,080 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.16, EMA_12: 0.16)
2025-06-21 11:25:04,080 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:25:04,080 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:25:04,095 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:26:04,099 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:26:05,283 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:26:05,315 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.16, EMA_12: 0.16)
2025-06-21 11:26:05,315 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:26:05,315 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:26:05,322 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:27:05,326 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:27:05,723 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:27:05,741 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.16, EMA_12: 0.16)
2025-06-21 11:27:05,741 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:27:05,741 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:27:05,741 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:28:05,750 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:28:06,113 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:28:06,144 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.16, EMA_12: 0.16)
2025-06-21 11:28:06,146 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:28:06,146 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:28:06,147 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:29:06,151 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:29:06,788 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:29:06,806 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.16, EMA_12: 0.16)
2025-06-21 11:29:06,815 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:29:06,816 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:29:06,816 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:58:05,070 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 11:58:05,070 - root - INFO - Bot initialized in TEST environment.
2025-06-21 11:58:05,070 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:58:05,275 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:58:05,309 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.72, EMA_12: 0.16)
2025-06-21 11:58:05,310 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:58:05,310 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:58:05,311 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 11:59:05,314 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 11:59:05,472 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 11:59:05,522 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.72, EMA_12: 0.16)
2025-06-21 11:59:05,524 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 11:59:05,524 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 11:59:05,525 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:00:05,528 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:00:05,684 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:00:05,731 - modules.ta_engine - INFO - TA Score Calculated: -6.00 (RSI: 40.17, EMA_12: 0.16)
2025-06-21 12:00:05,732 - root - INFO - Checking for entry signal. Current TA Score: -6.00
2025-06-21 12:00:05,733 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 12:15:05,737 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:15:05,925 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:15:05,933 - modules.ta_engine - INFO - TA Score Calculated: -6.00 (RSI: 50.17, EMA_12: 0.16)
2025-06-21 12:15:05,934 - root - INFO - Checking for entry signal. Current TA Score: -6.00
2025-06-21 12:15:05,934 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 12:30:05,936 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:30:06,144 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:30:06,152 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.54, EMA_12: 0.16)
2025-06-21 12:30:06,153 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:30:06,153 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:30:06,154 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:31:06,170 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:31:06,311 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:31:06,322 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.54, EMA_12: 0.16)
2025-06-21 12:31:06,322 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:31:06,323 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:31:06,323 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:32:06,326 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:32:06,459 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:32:06,467 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.54, EMA_12: 0.16)
2025-06-21 12:32:06,467 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:32:06,468 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:32:06,468 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:33:06,471 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:33:06,606 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:33:06,616 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.54, EMA_12: 0.16)
2025-06-21 12:33:06,617 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:33:06,617 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:33:06,617 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:34:06,619 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:34:06,766 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:34:06,776 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.54, EMA_12: 0.16)
2025-06-21 12:34:06,777 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:34:06,777 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:34:06,777 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:35:06,779 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:35:06,990 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:35:06,997 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.54, EMA_12: 0.16)
2025-06-21 12:35:06,997 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:35:06,998 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:35:06,998 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:36:07,002 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:36:07,143 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:36:07,152 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.54, EMA_12: 0.16)
2025-06-21 12:36:07,152 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:36:07,153 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:36:07,153 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:37:07,156 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:37:07,296 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:37:07,310 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.54, EMA_12: 0.16)
2025-06-21 12:37:07,311 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:37:07,312 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:37:07,312 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:38:07,315 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:38:07,456 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:38:07,470 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.54, EMA_12: 0.16)
2025-06-21 12:38:07,471 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:38:07,471 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:38:07,472 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:39:07,474 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:39:07,619 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:39:07,628 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.54, EMA_12: 0.16)
2025-06-21 12:39:07,628 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:39:07,628 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:39:07,628 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:40:07,631 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:40:07,901 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:40:07,908 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.54, EMA_12: 0.16)
2025-06-21 12:40:07,909 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:40:07,910 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:40:07,910 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:41:07,913 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:41:08,057 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:41:08,064 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.54, EMA_12: 0.16)
2025-06-21 12:41:08,064 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:41:08,065 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:41:08,065 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:42:08,068 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:42:08,213 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:42:08,224 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.54, EMA_12: 0.16)
2025-06-21 12:42:08,225 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:42:08,226 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:42:08,226 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:43:08,229 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:43:08,368 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:43:08,379 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.54, EMA_12: 0.16)
2025-06-21 12:43:08,380 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:43:08,380 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:43:08,380 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:44:08,382 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:44:08,523 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:44:08,533 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 52.54, EMA_12: 0.16)
2025-06-21 12:44:08,534 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:44:08,534 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:44:08,535 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:45:08,537 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:45:08,756 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:45:08,763 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 49.50, EMA_12: 0.16)
2025-06-21 12:45:08,763 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:45:08,765 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:45:08,765 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:46:08,768 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:46:08,909 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:46:08,922 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 49.50, EMA_12: 0.16)
2025-06-21 12:46:08,922 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:46:08,923 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:46:08,923 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:47:08,925 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:47:09,081 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:47:09,090 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 49.50, EMA_12: 0.16)
2025-06-21 12:47:09,091 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:47:09,092 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:47:09,093 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:48:09,096 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:48:09,238 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:48:09,251 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 49.50, EMA_12: 0.16)
2025-06-21 12:48:09,252 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:48:09,252 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:48:09,253 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:49:09,255 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:49:09,399 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:49:09,411 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 49.50, EMA_12: 0.16)
2025-06-21 12:49:09,412 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:49:09,412 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:49:09,413 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:50:09,415 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:50:09,641 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:50:09,652 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 49.50, EMA_12: 0.16)
2025-06-21 12:50:09,652 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:50:09,653 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:50:09,653 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:51:09,655 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:51:09,792 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:51:09,801 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 49.50, EMA_12: 0.16)
2025-06-21 12:51:09,802 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:51:09,802 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:51:09,803 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:52:09,805 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:52:09,939 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:52:09,947 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 49.50, EMA_12: 0.16)
2025-06-21 12:52:09,948 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:52:09,948 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:52:09,949 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:53:09,952 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:53:10,093 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:53:10,100 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 49.50, EMA_12: 0.16)
2025-06-21 12:53:10,101 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:53:10,102 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:53:10,102 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:54:10,104 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:54:10,251 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:54:10,260 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 49.50, EMA_12: 0.16)
2025-06-21 12:54:10,260 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:54:10,261 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:54:10,261 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:55:10,263 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:55:10,442 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:55:10,451 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 49.50, EMA_12: 0.16)
2025-06-21 12:55:10,452 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:55:10,453 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:55:10,453 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:56:10,455 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:56:10,598 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:56:10,608 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 49.50, EMA_12: 0.16)
2025-06-21 12:56:10,609 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:56:10,609 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:56:10,610 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:57:10,612 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:57:10,753 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:57:10,763 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 49.50, EMA_12: 0.16)
2025-06-21 12:57:10,763 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:57:10,764 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:57:10,764 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:58:10,767 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:58:10,908 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:58:10,916 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 49.50, EMA_12: 0.16)
2025-06-21 12:58:10,917 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:58:10,918 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:58:10,919 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 12:59:10,922 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 12:59:11,065 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 12:59:11,072 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 49.50, EMA_12: 0.16)
2025-06-21 12:59:11,073 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 12:59:11,073 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 12:59:11,074 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 13:00:11,075 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:00:11,281 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:00:11,290 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 51.51, EMA_12: 0.16)
2025-06-21 13:00:11,290 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:00:11,291 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:00:11,291 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 13:01:11,293 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:01:11,435 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:01:11,443 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 51.51, EMA_12: 0.16)
2025-06-21 13:01:11,444 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:01:11,445 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:01:11,445 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 13:02:11,448 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:02:11,591 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:02:11,605 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 51.51, EMA_12: 0.16)
2025-06-21 13:02:11,606 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:02:11,607 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:02:11,608 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 120, in start
    try:
        
  File "D:\file\bot_okx_future\bot.py", line 45, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 56, in check_for_entry
    instrument_details = self.api.get_instrument_details(config.SYMBOL)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_instrument_details'
2025-06-21 13:03:11,610 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:03:11,787 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:03:11,798 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 51.51, EMA_12: 0.16)
2025-06-21 13:03:11,798 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:03:11,799 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:04:11,874 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:04:12,016 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:04:12,027 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 51.51, EMA_12: 0.16)
2025-06-21 13:04:12,027 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:04:12,028 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:05:12,035 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:05:12,202 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:05:12,241 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 51.51, EMA_12: 0.16)
2025-06-21 13:05:12,242 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:05:12,243 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:06:12,267 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:06:12,428 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:06:12,470 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 51.51, EMA_12: 0.16)
2025-06-21 13:06:12,475 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:06:12,476 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:07:12,502 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:07:12,651 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:07:12,672 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 51.51, EMA_12: 0.16)
2025-06-21 13:07:12,673 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:07:12,673 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:08:12,691 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:08:12,908 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:08:12,916 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 51.51, EMA_12: 0.16)
2025-06-21 13:08:12,917 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:08:12,917 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:08:54,558 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 13:08:54,559 - root - INFO - Bot initialized in TEST environment.
2025-06-21 13:08:54,559 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:08:54,559 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 24, in run_cycle
    klines = self.api.get_klines(config.SYMBOL, config.TIMEFRAME, total_candles=100)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\modules\api_integration.py", line 88, in get_klines
    headers = self._get_headers(method, request_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\modules\api_integration.py", line 39, in _get_headers
    timestamp = self._get_timestamp()
                ^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\modules\api_integration.py", line 25, in _get_timestamp
    return time.strftime('%Y-%m-%dT%H:%M:%S.%3fZ', time.gmtime())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid format string
2025-06-21 13:09:54,561 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:09:54,561 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 24, in run_cycle
    klines = self.api.get_klines(config.SYMBOL, config.TIMEFRAME, total_candles=100)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\modules\api_integration.py", line 88, in get_klines
    headers = self._get_headers(method, request_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\modules\api_integration.py", line 39, in _get_headers
    timestamp = self._get_timestamp()
                ^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\modules\api_integration.py", line 25, in _get_timestamp
    return time.strftime('%Y-%m-%dT%H:%M:%S.%3fZ', time.gmtime())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid format string
2025-06-21 13:10:54,564 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:10:54,564 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 24, in run_cycle
    klines = self.api.get_klines(config.SYMBOL, config.TIMEFRAME, total_candles=100)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\modules\api_integration.py", line 88, in get_klines
    headers = self._get_headers(method, request_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\modules\api_integration.py", line 39, in _get_headers
    timestamp = self._get_timestamp()
                ^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\modules\api_integration.py", line 25, in _get_timestamp
    return time.strftime('%Y-%m-%dT%H:%M:%S.%3fZ', time.gmtime())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid format string
2025-06-21 13:11:54,568 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:11:54,568 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 24, in run_cycle
    klines = self.api.get_klines(config.SYMBOL, config.TIMEFRAME, total_candles=100)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\modules\api_integration.py", line 88, in get_klines
    headers = self._get_headers(method, request_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\modules\api_integration.py", line 39, in _get_headers
    timestamp = self._get_timestamp()
                ^^^^^^^^^^^^^^^^^^^^^
  File "D:\file\bot_okx_future\modules\api_integration.py", line 25, in _get_timestamp
    return time.strftime('%Y-%m-%dT%H:%M:%S.%3fZ', time.gmtime())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid format string
2025-06-21 13:12:45,168 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 13:13:42,838 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 13:13:42,838 - root - INFO - Bot initialized in TEST environment.
2025-06-21 13:13:42,839 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:13:42,839 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 24, in run_cycle
    klines = self.api.get_klines(config.SYMBOL, config.TIMEFRAME, total_candles=100)
             ^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_klines'
2025-06-21 13:14:42,841 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:14:42,842 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 24, in run_cycle
    klines = self.api.get_klines(config.SYMBOL, config.TIMEFRAME, total_candles=100)
             ^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_klines'
2025-06-21 13:15:42,847 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:15:42,847 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 24, in run_cycle
    klines = self.api.get_klines(config.SYMBOL, config.TIMEFRAME, total_candles=100)
             ^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_klines'
2025-06-21 13:16:42,849 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:16:42,849 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 24, in run_cycle
    klines = self.api.get_klines(config.SYMBOL, config.TIMEFRAME, total_candles=100)
             ^^^^^^^^^^^^^^^^^^^
AttributeError: 'OKXIntegration' object has no attribute 'get_klines'
2025-06-21 13:16:55,542 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 13:16:55,542 - root - INFO - Bot initialized in TEST environment.
2025-06-21 13:16:55,542 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:16:55,757 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:16:55,766 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 62.11, EMA_12: 0.16)
2025-06-21 13:16:55,767 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:16:55,767 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:16:55,946 - modules.api_integration - INFO - Available balance for USDT: 54780.12080624591
2025-06-21 13:16:55,946 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 39, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 63, in check_for_entry
    size = risk_manager.get_position_size(trade_params['entry'], trade_params['sl'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RiskManagement' object has no attribute 'get_position_size'
2025-06-21 13:17:55,949 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:17:56,087 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:17:56,095 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 62.11, EMA_12: 0.16)
2025-06-21 13:17:56,096 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:17:56,097 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:17:56,227 - modules.api_integration - INFO - Available balance for USDT: 54780.12080624591
2025-06-21 13:17:56,228 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 39, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 63, in check_for_entry
    size = risk_manager.get_position_size(trade_params['entry'], trade_params['sl'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RiskManagement' object has no attribute 'get_position_size'
2025-06-21 13:18:56,230 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:18:56,372 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:18:56,381 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 62.11, EMA_12: 0.16)
2025-06-21 13:18:56,382 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:18:56,382 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:18:56,515 - modules.api_integration - INFO - Available balance for USDT: 54780.12080624591
2025-06-21 13:18:56,516 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 39, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 63, in check_for_entry
    size = risk_manager.get_position_size(trade_params['entry'], trade_params['sl'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RiskManagement' object has no attribute 'get_position_size'
2025-06-21 13:19:56,518 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:19:56,667 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:19:56,675 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 62.11, EMA_12: 0.16)
2025-06-21 13:19:56,675 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:19:56,676 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:19:56,807 - modules.api_integration - INFO - Available balance for USDT: 54780.12080624591
2025-06-21 13:19:56,808 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 39, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 63, in check_for_entry
    size = risk_manager.get_position_size(trade_params['entry'], trade_params['sl'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RiskManagement' object has no attribute 'get_position_size'
2025-06-21 13:20:56,810 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:20:56,952 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:20:56,960 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 62.11, EMA_12: 0.16)
2025-06-21 13:20:56,961 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:20:56,961 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:20:57,098 - modules.api_integration - INFO - Available balance for USDT: 54780.12080624591
2025-06-21 13:20:57,099 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 39, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 63, in check_for_entry
    size = risk_manager.get_position_size(trade_params['entry'], trade_params['sl'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RiskManagement' object has no attribute 'get_position_size'
2025-06-21 13:21:57,101 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:21:57,307 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:21:57,314 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 62.11, EMA_12: 0.16)
2025-06-21 13:21:57,314 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:21:57,315 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:21:57,447 - modules.api_integration - INFO - Available balance for USDT: 54780.12080624591
2025-06-21 13:21:57,448 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 39, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 63, in check_for_entry
    size = risk_manager.get_position_size(trade_params['entry'], trade_params['sl'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RiskManagement' object has no attribute 'get_position_size'
2025-06-21 13:22:57,450 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:22:57,599 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:22:57,609 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 62.11, EMA_12: 0.16)
2025-06-21 13:22:57,610 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:22:57,610 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:22:57,742 - modules.api_integration - INFO - Available balance for USDT: 54780.12080624591
2025-06-21 13:22:57,744 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 39, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 63, in check_for_entry
    size = risk_manager.get_position_size(trade_params['entry'], trade_params['sl'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RiskManagement' object has no attribute 'get_position_size'
2025-06-21 13:23:57,747 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:23:57,890 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:23:57,898 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 62.11, EMA_12: 0.16)
2025-06-21 13:23:57,899 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:23:57,900 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:23:58,032 - modules.api_integration - INFO - Available balance for USDT: 54780.12080624591
2025-06-21 13:23:58,033 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 39, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 63, in check_for_entry
    size = risk_manager.get_position_size(trade_params['entry'], trade_params['sl'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RiskManagement' object has no attribute 'get_position_size'
2025-06-21 13:24:58,040 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:24:58,182 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:24:58,201 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 62.11, EMA_12: 0.16)
2025-06-21 13:24:58,201 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:24:58,202 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:24:58,327 - modules.api_integration - INFO - Available balance for USDT: 54780.12080624591
2025-06-21 13:24:58,328 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 39, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 63, in check_for_entry
    size = risk_manager.get_position_size(trade_params['entry'], trade_params['sl'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RiskManagement' object has no attribute 'get_position_size'
2025-06-21 13:25:58,330 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:25:58,485 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:25:58,503 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 62.11, EMA_12: 0.16)
2025-06-21 13:25:58,504 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:25:58,505 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:25:58,637 - modules.api_integration - INFO - Available balance for USDT: 54780.12080624591
2025-06-21 13:25:58,638 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 39, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 63, in check_for_entry
    size = risk_manager.get_position_size(trade_params['entry'], trade_params['sl'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RiskManagement' object has no attribute 'get_position_size'
2025-06-21 13:26:58,640 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:26:58,938 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:26:58,946 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 62.11, EMA_12: 0.16)
2025-06-21 13:26:58,947 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:26:58,947 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:26:59,080 - modules.api_integration - INFO - Available balance for USDT: 54780.12080624591
2025-06-21 13:26:59,081 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 39, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 63, in check_for_entry
    size = risk_manager.get_position_size(trade_params['entry'], trade_params['sl'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RiskManagement' object has no attribute 'get_position_size'
2025-06-21 13:27:59,083 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:27:59,232 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:27:59,240 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 62.11, EMA_12: 0.16)
2025-06-21 13:27:59,240 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:27:59,241 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:27:59,385 - modules.api_integration - INFO - Available balance for USDT: 54780.12080624591
2025-06-21 13:27:59,386 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 39, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 63, in check_for_entry
    size = risk_manager.get_position_size(trade_params['entry'], trade_params['sl'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RiskManagement' object has no attribute 'get_position_size'
2025-06-21 13:28:59,388 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:28:59,533 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:28:59,540 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 62.11, EMA_12: 0.16)
2025-06-21 13:28:59,540 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:28:59,541 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:28:59,672 - modules.api_integration - INFO - Available balance for USDT: 54780.12080624591
2025-06-21 13:28:59,673 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 39, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 63, in check_for_entry
    size = risk_manager.get_position_size(trade_params['entry'], trade_params['sl'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RiskManagement' object has no attribute 'get_position_size'
2025-06-21 13:29:59,675 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:29:59,814 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:29:59,822 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 49.20, EMA_12: 0.16)
2025-06-21 13:29:59,823 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:29:59,824 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:29:59,967 - modules.api_integration - INFO - Available balance for USDT: 54780.12080624591
2025-06-21 13:29:59,968 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 39, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 63, in check_for_entry
    size = risk_manager.get_position_size(trade_params['entry'], trade_params['sl'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RiskManagement' object has no attribute 'get_position_size'
2025-06-21 13:30:59,970 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:31:00,115 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:31:00,123 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 49.20, EMA_12: 0.16)
2025-06-21 13:31:00,123 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:31:00,124 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:31:00,287 - modules.api_integration - INFO - Available balance for USDT: 54780.12080624591
2025-06-21 13:31:00,288 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 39, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 63, in check_for_entry
    size = risk_manager.get_position_size(trade_params['entry'], trade_params['sl'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RiskManagement' object has no attribute 'get_position_size'
2025-06-21 13:32:00,290 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:32:00,474 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:32:00,481 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 49.20, EMA_12: 0.16)
2025-06-21 13:32:00,482 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:32:00,482 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:32:00,612 - modules.api_integration - INFO - Available balance for USDT: 54780.12080624591
2025-06-21 13:32:00,613 - root - ERROR - An unexpected error occurred in the main loop!
Traceback (most recent call last):
  File "D:\file\bot_okx_future\bot.py", line 107, in start
    self.run_cycle()
  File "D:\file\bot_okx_future\bot.py", line 39, in run_cycle
    self.check_for_entry(ta_score, latest_candle)
  File "D:\file\bot_okx_future\bot.py", line 63, in check_for_entry
    size = risk_manager.get_position_size(trade_params['entry'], trade_params['sl'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RiskManagement' object has no attribute 'get_position_size'
2025-06-21 13:33:42,737 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 13:33:42,738 - root - INFO - Bot initialized in TEST environment.
2025-06-21 13:33:42,738 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:33:42,889 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:33:42,898 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 49.20, EMA_12: 0.16)
2025-06-21 13:33:42,899 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:33:42,899 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:33:43,165 - modules.api_integration - INFO - Available balance for USDT: 54,780.12
2025-06-21 13:33:43,166 - modules.risk_management - INFO - Risk Calc: Balance=$54,780.12, Risk=$547.80, Raw Size=150559.5568, Adjusted Size=150559.5500, Lot Size=0.01
2025-06-21 13:33:43,301 - modules.api_integration - INFO - Placing order: buy 150559.55000000002 DOGE-USDT-SWAP
2025-06-21 13:33:43,302 - root - ERROR - Failed to place trade. API Response: {'code': '1', 'data': [{'clOrdId': '', 'ordId': '', 'sCode': '51121', 'sMsg': 'Order quantity must be a multiple of the lot size.', 'tag': '', 'ts': '1750487625134'}], 'inTime': '1750487625133878', 'msg': 'All operations failed', 'outTime': '1750487625134046'}
2025-06-21 13:33:43,302 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 13:34:15,189 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 13:34:15,189 - root - INFO - Bot initialized in TEST environment.
2025-06-21 13:34:15,189 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:34:15,343 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:34:15,352 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 49.20, EMA_12: 0.16)
2025-06-21 13:34:15,353 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:34:15,353 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:34:15,605 - modules.api_integration - INFO - Available balance for USDT: 54,780.12
2025-06-21 13:34:15,606 - modules.risk_management - INFO - Risk Calc: Balance=$54,780.12, Risk=$547.80, Raw Size=150559.5568, Adjusted Size=150559.5500, Lot Size=0.01
2025-06-21 13:34:15,729 - modules.api_integration - INFO - Placing order: buy 150559.55000000002 DOGE-USDT-SWAP
2025-06-21 13:34:15,730 - root - ERROR - Failed to place trade. API Response: {'code': '1', 'data': [{'clOrdId': '', 'ordId': '', 'sCode': '51121', 'sMsg': 'Order quantity must be a multiple of the lot size.', 'tag': '', 'ts': '1750487657563'}], 'inTime': '1750487657563162', 'msg': 'All operations failed', 'outTime': '1750487657563334'}
2025-06-21 13:34:15,731 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 13:46:07,747 - root - INFO - Bot stopped by user.
2025-06-21 13:46:15,983 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 13:46:15,983 - root - INFO - Bot initialized in TEST environment.
2025-06-21 13:47:48,767 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 13:47:48,768 - root - INFO - Bot initialized in TEST environment.
2025-06-21 13:47:48,768 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:47:48,980 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:47:48,988 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 48.82, EMA_12: 0.16)
2025-06-21 13:47:48,989 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:47:48,990 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:47:49,254 - modules.api_integration - INFO - Available balance for USDT: 54,780.12
2025-06-21 13:47:49,255 - modules.risk_management - INFO - Risk Calc: Balance=$54,780.12, Risk=$547.80, Raw Size=160310.8606, Adjusted Size=160310.8600, Lot Size=0.01
2025-06-21 13:47:49,256 - root - INFO - Final formatted size to be placed: 160310.86
2025-06-21 13:47:49,392 - modules.api_integration - INFO - Placing order: buy 160310.86 DOGE-USDT-SWAP
2025-06-21 13:47:49,392 - root - ERROR - Failed to place trade. API Response: {'code': '1', 'data': [{'clOrdId': '', 'ordId': '', 'sCode': '51000', 'sMsg': 'Parameter posSide error ', 'tag': '', 'ts': '1750488471229'}], 'inTime': '1750488471229635', 'msg': 'All operations failed', 'outTime': '1750488471230739'}
2025-06-21 13:47:49,393 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 13:52:40,134 - root - INFO - Bot stopped by user.
2025-06-21 13:52:45,397 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 13:52:45,397 - root - INFO - Bot initialized in TEST environment.
2025-06-21 13:52:45,398 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:52:45,545 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:52:45,554 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 48.82, EMA_12: 0.16)
2025-06-21 13:52:45,555 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:52:45,555 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:52:45,823 - modules.api_integration - INFO - Available balance for USDT: 54,780.12
2025-06-21 13:52:45,824 - modules.risk_management - INFO - Risk Calc: Balance=$54,780.12, Risk=$547.80, Raw Size=160310.8606, Adjusted Size=160310.8600, Lot Size=0.01
2025-06-21 13:52:45,825 - root - INFO - Final formatted size to be placed: 160310.86
2025-06-21 13:52:45,961 - modules.api_integration - INFO - Placing order: buy 160310.86 DOGE-USDT-SWAP
2025-06-21 13:52:45,962 - root - ERROR - Failed to place trade. API Response: {'code': '1', 'data': [{'clOrdId': '', 'ordId': '', 'sCode': '51202', 'sMsg': 'Market order amount exceeds the maximum amount. ', 'tag': '', 'ts': '1750488767802'}], 'inTime': '1750488767801972', 'msg': 'All operations failed', 'outTime': '1750488767802990'}
2025-06-21 13:52:45,962 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 13:54:18,730 - root - INFO - Bot stopped by user.
2025-06-21 13:54:20,707 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 13:54:20,707 - root - INFO - Bot initialized in TEST environment.
2025-06-21 13:54:20,708 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:54:20,890 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:54:20,902 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 48.82, EMA_12: 0.16)
2025-06-21 13:54:20,902 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:54:20,903 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:54:21,168 - modules.api_integration - INFO - Available balance for USDT: 54,780.12
2025-06-21 13:54:21,169 - modules.risk_management - INFO - Risk Calc: Balance=$54,780.12, Risk=$54.78, Raw Size=16031.0861, Adjusted Size=16031.0800, Lot Size=0.01
2025-06-21 13:54:21,170 - root - INFO - Final formatted size to be placed: 16031.08
2025-06-21 13:54:21,310 - modules.api_integration - INFO - Placing order: buy 16031.08 DOGE-USDT-SWAP
2025-06-21 13:54:21,313 - root - ERROR - Failed to place trade. API Response: {'code': '1', 'data': [{'clOrdId': '', 'ordId': '', 'sCode': '51202', 'sMsg': 'Market order amount exceeds the maximum amount. ', 'tag': '', 'ts': '1750488863150'}], 'inTime': '1750488863150221', 'msg': 'All operations failed', 'outTime': '1750488863151251'}
2025-06-21 13:54:21,313 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 13:55:21,726 - root - INFO - Bot stopped by user.
2025-06-21 13:55:24,896 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 13:55:24,896 - root - INFO - Bot initialized in TEST environment.
2025-06-21 13:55:24,896 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 13:55:25,045 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 13:55:25,054 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 48.82, EMA_12: 0.16)
2025-06-21 13:55:25,054 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 13:55:25,055 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 13:55:25,308 - modules.api_integration - INFO - Available balance for USDT: 54,780.12
2025-06-21 13:55:25,309 - modules.risk_management - INFO - Risk Calc: Balance=$54,780.12, Risk=$5.48, Raw Size=1603.1086, Adjusted Size=1603.1000, Lot Size=0.01
2025-06-21 13:55:25,309 - root - INFO - Final formatted size to be placed: 1603.10
2025-06-21 13:55:25,441 - modules.api_integration - INFO - Placing order: buy 1603.10 DOGE-USDT-SWAP
2025-06-21 13:55:25,442 - root - ERROR - Failed to place trade. API Response: {'code': '1', 'data': [{'clOrdId': '', 'ordId': '', 'sCode': '51008', 'sMsg': 'Order failed. Insufficient USDT margin in account ', 'tag': '', 'ts': '1750488927283'}], 'inTime': '1750488927283198', 'msg': 'All operations failed', 'outTime': '1750488927284128'}
2025-06-21 13:55:25,443 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 14:08:47,546 - root - INFO - Bot stopped by user.
2025-06-21 14:08:51,874 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 14:08:51,874 - root - INFO - Bot initialized in TEST environment.
2025-06-21 14:08:51,875 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 14:08:52,065 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 14:08:52,073 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 49.65, EMA_12: 0.16)
2025-06-21 14:08:52,074 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 14:08:52,074 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 14:08:52,331 - modules.api_integration - INFO - Available balance for USDT: 54,780.12
2025-06-21 14:08:52,332 - modules.risk_management - INFO - Risk Calc: Balance=$54,780.12, Risk=$5.48, Raw Size=1712.5462, Adjusted Size=1712.5400, Lot Size=0.01
2025-06-21 14:08:52,332 - root - INFO - Final formatted size to be placed: 1712.54
2025-06-21 14:08:52,464 - modules.api_integration - INFO - Placing order: buy 1712.54 DOGE-USDT-SWAP
2025-06-21 14:08:52,465 - root - ERROR - Failed to place trade. API Response: {'code': '1', 'data': [{'clOrdId': '', 'ordId': '', 'sCode': '51008', 'sMsg': 'Order failed. Insufficient USDT margin in account ', 'tag': '', 'ts': '1750489734310'}], 'inTime': '1750489734310558', 'msg': 'All operations failed', 'outTime': '1750489734311203'}
2025-06-21 14:08:52,466 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 14:17:21,998 - root - INFO - Bot stopped by user.
2025-06-21 14:17:27,597 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 14:17:27,597 - root - INFO - Bot initialized in TEST environment.
2025-06-21 14:17:27,598 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 14:17:27,833 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 14:17:27,842 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 45.29, EMA_12: 0.16)
2025-06-21 14:17:27,843 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 14:17:27,843 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 14:17:28,129 - modules.api_integration - INFO - Available balance for USDT: 115,844.80
2025-06-21 14:17:28,130 - modules.risk_management - INFO - Risk Calc: Balance=$115,844.80, Risk=$11.58, Raw Size=3833.7637, Adjusted Size=3833.7600, Lot Size=0.01
2025-06-21 14:17:28,130 - root - INFO - Final formatted size to be placed: 3833.76
2025-06-21 14:17:28,278 - modules.api_integration - INFO - Placing order: buy 3833.76 DOGE-USDT-SWAP
2025-06-21 14:17:28,279 - root - ERROR - Failed to place trade. API Response: {'code': '1', 'data': [{'clOrdId': '', 'ordId': '', 'sCode': '51008', 'sMsg': 'Order failed. Insufficient USDT margin in account ', 'tag': '', 'ts': '1750490250122'}], 'inTime': '1750490250121993', 'msg': 'All operations failed', 'outTime': '1750490250122767'}
2025-06-21 14:17:28,280 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 14:17:56,000 - root - INFO - Bot stopped by user.
2025-06-21 14:27:49,472 - root - INFO - Initializing Trading Bot (Live/Paper Mode)...
2025-06-21 14:27:49,473 - root - INFO - Bot initialized in TEST environment.
2025-06-21 14:27:49,473 - root - INFO - --- Running new cycle for DOGE-USDT-SWAP ---
2025-06-21 14:27:49,649 - modules.api_integration - INFO - Successfully fetched 300 klines for DOGE-USDT-SWAP
2025-06-21 14:27:49,658 - modules.ta_engine - INFO - TA Score Calculated: 6.00 (RSI: 45.29, EMA_12: 0.16)
2025-06-21 14:27:49,659 - root - INFO - Checking for entry signal. Current TA Score: 6.00
2025-06-21 14:27:49,660 - root - INFO - ENTRY SIGNAL DETECTED! Attempting to place a BUY order.
2025-06-21 14:27:49,916 - modules.api_integration - INFO - Available balance for USDT: 115,844.80
2025-06-21 14:27:49,917 - modules.risk_management - INFO - Risk Calc: Balance=$115,844.80, Risk=$11.58, Raw Size=3833.7637, Adjusted Size=3833.7600, Lot Size=0.01
2025-06-21 14:27:49,917 - root - INFO - Final formatted size to be placed: 3833.76
2025-06-21 14:27:50,069 - modules.api_integration - INFO - Placing order: buy 3833.76 DOGE-USDT-SWAP
2025-06-21 14:27:50,070 - root - ERROR - Failed to place trade. API Response: {'code': '1', 'data': [{'clOrdId': '', 'ordId': '', 'sCode': '51008', 'sMsg': 'Order failed. Insufficient USDT margin in account ', 'tag': '', 'ts': '1750490871925'}], 'inTime': '1750490871925164', 'msg': 'All operations failed', 'outTime': '1750490871926269'}
2025-06-21 14:27:50,071 - root - INFO - Cycle finished. Waiting for 900 seconds...
2025-06-21 14:29:46,558 - root - INFO - Bot stopped by user.
